### ISSUE TITLE
Adding Github & RCOS Logos

### ISSUE THREAD

**Issue by Raamzeez** [Raamzeez/IntelliSlides#5]
Since IntelliSlides has recently become open source and is officially a part of RCOS, it would be nice to have Github and RCOS logos in appropriate places, such as the bottom of the home page, and perhaps in the footer of the app page. The logos should be responsive and should be clickable. When you click on them, it should open a new tab with the appropriate link. If the user clicks on the Github icon, it should bring them to this Github repository, and if they click on the RCOS logo, it should bring them to the RCOS home page.

**Comment by kfreemantle** [comment]
I'd like to attempt a PR for this today as a first-time contributor.

**Comment by Raamzeez** [comment]
@kfreemantle Yup, no problem! Feel free to work on it! If you get stuck with anything let me know, although I just made this project open source a few days ago for school so I'm also learning myself 😄. You can also join the discord here if you want to communicate easier: https://discord.gg/BFbTrBnqtp. If you finish the changes just open a PR request for the "testing" branch, not the "main" branch 👍🏽

**Comment by kfreemantle** [comment]
@Rapib and I have worked on this issue and submitted PRs to resolve the issue.  We added the Github and RCOS icons below the IntelliSlides 2023 text, centered with 10px padding between them.  Small task for two people but we both need the practice contributing!  

Thanks so much!

**Comment by Raamzeez** [comment]
I left the issue open because there is still some places that I would like to logo to be, like an RCOS logo on the left side of the bottom footer and the Github logo on the right side of the bottom footer. I would also like the logos in both the home page footer and the app page footer.

**Comment by Raamzeez** [comment]
The branch for this issue was reviewed, approved, and merged with the testing branch.
